name: Run Python Tests

on:
  push:

jobs:

  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2 
      
      - name: Python tests
        run: python test_utils.py
